import TaskModel from "../models/Task.model";

const tasksData: Array<TaskModel> = [
    {
        id: 0,
        listId: 0,
        title: "Buy milk",
        completed: false,
        due_date: undefined,
        priority: 2,
    },
    {
        id: 1,
        listId: 0,
        title: "Buy bread",
        completed: false,
        due_date: undefined,
        priority: 2,
    },
    {
        id: 2,
        listId: 0,
        title: "Buy vegetables",
        completed: false,
        due_date: undefined,
        priority: 1,
    },

    {
        id: 3,
        listId: 1,
        title: "Clean the kitchen",
        completed: false,
        due_date: undefined,
        priority: 3,
    },
    {
        id: 4,
        listId: 1,
        title: "Vacuum living room",
        completed: false,
        due_date: undefined,
        priority: 2,
    },
    {
        id: 5,
        listId: 1,
        title: "Laundry",
        completed: false,
        due_date: undefined,
        priority: 1,
    },

    {
        id: 6,
        listId: 2,
        title: "Morning run",
        completed: false,
        due_date: undefined,
        priority: 1,
    },
    {
        id: 7,
        listId: 2,
        title: "Gym session",
        completed: false,
        due_date: undefined,
        priority: 2,
    },
    {
        id: 8,
        listId: 2,
        title: "Yoga",
        completed: false,
        due_date: undefined,
        priority: 3,
    },

    {
        id: 9,
        listId: 3,
        title: "Team meeting",
        completed: false,
        due_date: new Date('2024-07-14'),
        priority: 1,
    },
    {
        id: 10,
        listId: 3,
        title: "Client call",
        completed: false,
        due_date: new Date('2024-07-15'),
        priority: 2,
    },
    {
        id: 11,
        listId: 3,
        title: "Project update",
        completed: false,
        due_date: new Date('2024-07-16'),
        priority: 3,
    },

    {
        id: 12,
        listId: 4,
        title: "Submit report",
        completed: false,
        due_date: new Date('2024-07-20'),
        priority: 1,
    },
    {
        id: 13,
        listId: 4,
        title: "Finish presentation",
        completed: false,
        due_date: new Date('2024-07-18'),
        priority: 2,
    },
    {
        id: 14,
        listId: 4,
        title: "Review budget",
        completed: false,
        due_date: new Date('2024-07-19'),
        priority: 3,
    },

    {
        id: 15,
        listId: 5,
        title: "Email responses",
        completed: false,
        due_date: undefined,
        priority: 2,
    },
    {
        id: 16,
        listId: 5,
        title: "Prepare documents",
        completed: false,
        due_date: undefined,
        priority: 3,
    },
    {
        id: 17,
        listId: 5,
        title: "Schedule appointments",
        completed: false,
        due_date: undefined,
        priority: 1,
    },

    {
        id: 18,
        listId: 6,
        title: "Math homework",
        completed: false,
        due_date: new Date('2024-07-13'),
        priority: 1,
    },
    {
        id: 19,
        listId: 6,
        title: "Science project",
        completed: false,
        due_date: new Date('2024-07-20'),
        priority: 2,
    },
    {
        id: 20,
        listId: 6,
        title: "English essay",
        completed: false,
        due_date: new Date('2024-07-19'),
        priority: 3,
    },

    {
        id: 21,
        listId: 7,
        title: "Chapter 1 of biology",
        completed: false,
        due_date: undefined,
        priority: 1,
    },
    {
        id: 22,
        listId: 7,
        title: "Chapter 2 of history",
        completed: false,
        due_date: undefined,
        priority: 2,
    },
    {
        id: 23,
        listId: 7,
        title: "Novel for literature",
        completed: false,
        due_date: undefined,
        priority: 3,
    },

    {
        id: 24,
        listId: 8,
        title: "Math exam prep",
        completed: false,
        due_date: new Date('2024-07-15'),
        priority: 1,
    },
    {
        id: 25,
        listId: 8,
        title: "History exam prep",
        completed: false,
        due_date: new Date('2024-07-18'),
        priority: 2,
    },
    {
        id: 26,
        listId: 8,
        title: "Biology exam prep",
        completed: false,
        due_date: new Date('2024-07-20'),
        priority: 3,
    },

    {
        id: 27,
        listId: 9,
        title: "Watch lecture 1",
        completed: false,
        due_date: undefined,
        priority: 2,
    },
    {
        id: 28,
        listId: 9,
        title: "Watch lecture 2",
        completed: false,
        due_date: undefined,
        priority: 2,
    },
    {
        id: 29,
        listId: 9,
        title: "Watch lecture 3",
        completed: false,
        due_date: undefined,
        priority: 1,
    },

    {
        id: 30,
        listId: 10,
        title: "Exercise 1",
        completed: false,
        due_date: undefined,
        priority: 1,
    },
    {
        id: 31,
        listId: 10,
        title: "Exercise 2",
        completed: false,
        due_date: undefined,
        priority: 2,
    },
    {
        id: 32,
        listId: 10,
        title: "Exercise 3",
        completed: false,
        due_date: undefined,
        priority: 3,
    },

    {
        id: 33,
        listId: 11,
        title: "Project proposal",
        completed: false,
        due_date: new Date('2024-07-20'),
        priority: 1,
    },
    {
        id: 34,
        listId: 11,
        title: "Initial prototype",
        completed: false,
        due_date: new Date('2024-07-25'),
        priority: 2,
    },
    {
        id: 35,
        listId: 11,
        title: "Final report",
        completed: false,
        due_date: new Date('2024-07-30'),
        priority: 3,
    },
];

export default tasksData;